[package]
name = "rust-taplo"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
serde_json.workspace = true
taplo.workspace = true
toml.workspace = true
toml-test.workspace = true
toml-test-harness.workspace = true
