[package]
name = "rust-toml_edit"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
serde_json.workspace = true
toml_edit.workspace = true
toml-test.workspace = true
toml-test-harness.workspace = true
