#!/usr/bin/env node

let fs   = require('fs');
let toml = require('./dist/NPM/index.js')

let convert = (v) => {
	switch (typeof(v)) {
	case 'string':  return {type: 'string',  value: v}
	case 'bigint':  return {type: 'integer', value: v.toString()}
	case 'number':  return {type: 'float',   value: v.toString()}
	case 'boolean': return {type: 'bool',    value: v.toString()}
	case 'object':
		if (!v.constructor) {
			for (k in v)
				v[k] = convert(v[k])
			return v
		}
		switch (v.constructor.name) {
		case 'OffsetDateTime': return {type: 'datetime',        value: v.toISOString()}
		case 'LocalDateTime':  return {type: 'datetime-local',  value: v.toISOString()}
		case 'LocalDate':      return {type: 'date-local',      value: v.toISOString()}
		case 'LocalTime':      return {type: 'time-local',      value: v.toISOString()}
		case 'Array':          return v.map(convert)
		default:
			throw(`unknown type: ${v.constructor.name}`)
		}
	default:
		throw(`unknown type: ${typeof(v)}`)
	}
}

let t = toml.parse(fs.readFileSync(0, 'utf-8'), {joiner: "\n"})
for (k in t)
	t[k] = convert(t[k])
process.stdout.write(JSON.stringify(t, null, 4))
