#!/usr/bin/env python

import datetime, sys, toml

with open(sys.argv[1], 'rb') as fp:
    data = fp.read().decode()
start = datetime.datetime.now()
toml.loads(data)
print(f'{(datetime.datetime.now() - start).total_seconds():f}')
