#!/usr/bin/env python

import tomli, sys, datetime

with open(sys.argv[1], 'rb') as fp:
    data = fp.read().decode()
start = datetime.datetime.now()
tomli.loads(data)
print(f'{(datetime.datetime.now() - start).total_seconds():f}')
