#!/usr/bin/env python

import tomllib, sys, datetime

with open(sys.argv[1], 'rb') as fp:
    data = fp.read().decode()
start = datetime.datetime.now()
tomllib.loads(data)
print((datetime.datetime.now() - start).total_seconds())
