[package]
name = "rust-basic-toml"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
basic-toml.workspace = true
serde_json.workspace = true
toml.workspace = true
toml-test.workspace = true
toml-test-harness.workspace = true
