name: 'test'
on:   ['push']
jobs:
  test:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v3
    - run: |
        go install github.com/toml-lang/toml-test/cmd/toml-test@master
    - name: 'install'
      run: |
        sudo apt-get update
        sudo apt-get install zsh \
          ninja-build \
          python3-pip \
          bundler \
          opam \
          guile-2.2 \
          racket

        # Meson from Ubuntu is too old.
        pip3 install --user meson

        # Dart
        sudo apt-get install apt-transport-https
        wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/dart.gpg
        echo 'deb [signed-by=/usr/share/keyrings/dart.gpg arch=amd64] https://storage.googleapis.com/download.dartlang.org/linux/debian stable main' | sudo tee /etc/apt/sources.list.d/dart_stable.list
        sudo apt-get update
        sudo apt-get install dart

        # Roswell
        (
          cd $HOME
          curl -Ls https://github.com/roswell/roswell/releases/download/v23.10.14.114/roswell-23.10.14.114-linux-x86_64.tar.bz2 |
            tar xjf -
        )
    - name: 'setup'
      run: |
        export PATH=$PATH:"$HOME/roswell":"$(go env GOPATH)/bin"
        ./run check || exit 1
        ./run setup || exit 1
    - name: 'run'
      run: |
        export PATH=$PATH:"$HOME/roswell":"$(go env GOPATH)/bin"
        ./run run
